import { Page, Post, ReusableBlock, Category, MediaItem, User, GlobalSettings, Comment, Theme, PluginItem, MenuItem } from '@/types/cms';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_admin',
    name: 'Administrador Master',
    email: 'admin@nextblog.com',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    bio: 'Super Administrador do NextBlog CMS.',
    status: 'active',
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat_tech', name: 'Tecnologia & Dev', slug: 'tecnologia', description: 'Artigos sobre Next.js, React, APIs e arquitetura moderna', color: '#3b82f6', count: 5 },
  { id: 'cat_design', name: 'Design & UI/UX', slug: 'design', description: 'Práticas de tipografia, cores e design visual de interfaces', color: '#8b5cf6', count: 3 },
  { id: 'cat_growth', name: 'Marketing & SEO', slug: 'marketing', description: 'Estratégias para rankeamento orgânico e conversão', color: '#10b981', count: 4 },
  { id: 'cat_business', name: 'Casos de Sucesso', slug: 'negocios', description: 'Histórias reais de marcas que migraram para Next.js', color: '#f59e0b', count: 2 },
];

export const INITIAL_MEDIA: MediaItem[] = [
  {
    id: 'med_1',
    name: 'Hero Tech Moderno',
    url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&auto=format&fit=crop&q=80',
    type: 'image',
    size: '1.4 MB',
    dimensions: '1920x1080',
    mimeType: 'image/jpeg',
    altText: 'Placa de circuito tecnológico iluminada em tom azul e dourado',
    createdAt: '2026-03-10T10:00:00Z',
  },
  {
    id: 'med_2',
    name: 'Equipe Criativa Colaborando',
    url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&auto=format&fit=crop&q=80',
    type: 'image',
    size: '2.1 MB',
    dimensions: '2400x1600',
    mimeType: 'image/jpeg',
    altText: 'Profissionais reunidos em volta de laptops planejando projeto',
    createdAt: '2026-03-12T11:20:00Z',
  },
  {
    id: 'med_3',
    name: 'Workspace Minimalista',
    url: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
    type: 'image',
    size: '890 KB',
    dimensions: '1600x1066',
    mimeType: 'image/jpeg',
    altText: 'Mesa de escritório limpa com monitor e iluminação natural suave',
    createdAt: '2026-03-15T15:45:00Z',
  },
  {
    id: 'med_4',
    name: 'Código e Desenvolvimento Web',
    url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&auto=format&fit=crop&q=80',
    type: 'image',
    size: '1.8 MB',
    dimensions: '1920x1280',
    mimeType: 'image/jpeg',
    altText: 'Tela de computador exibindo código React e TypeScript estruturado',
    createdAt: '2026-03-18T08:30:00Z',
  },
  {
    id: 'med_5',
    name: 'Gráficos de Analytics e Performance',
    url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80',
    type: 'image',
    size: '1.2 MB',
    dimensions: '1800x1200',
    mimeType: 'image/jpeg',
    altText: 'Dashboard com métricas e gráficos de crescimento em alta resolução',
    createdAt: '2026-03-20T14:10:00Z',
  },
];

export const INITIAL_REUSABLE_BLOCKS: ReusableBlock[] = [
  {
    id: 'reuse_cta_master',
    title: 'Banner de Conversão Principal (CTA)',
    category: 'marketing',
    description: 'Chamada para ação de alta conversão com botão de destaque e badge.',
    usageCount: 4,
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-03-20T11:00:00Z',
    block: {
      id: 'block_cta_master',
      type: 'cta_banner',
      content: {
        tagline: 'COMECE AGORA MESMO',
        title: 'Pronto para elevar seu site com Next.js?',
        description: 'Construa experiências ultra-rápidas, personalizáveis e com a flexibilidade que seu time sempre sonhou.',
        primaryButtonText: 'Experimentar Gratuitamente',
        primaryButtonUrl: '#contato',
        secondaryButtonText: 'Ver Documentação',
        secondaryButtonUrl: '#api',
        styleVariant: 'gradient',
      },
      styles: {
        paddingY: 'large',
        borderRadius: 'lg',
      },
    },
  },
  {
    id: 'reuse_pricing_table',
    title: 'Tabela de Preços e Planos',
    category: 'commerce',
    description: 'Grade com 3 planos (Starter, Pro e Enterprise) com destaques e recursos.',
    usageCount: 2,
    createdAt: '2026-02-18T14:00:00Z',
    updatedAt: '2026-03-22T09:30:00Z',
    block: {
      id: 'block_pricing_main',
      type: 'pricing',
      content: {
        title: 'Planos Transparentes para Qualquer Escala',
        subtitle: 'Sem taxas ocultas. Cancele ou faça upgrade a qualquer momento.',
        plans: [
          {
            name: 'Iniciante',
            price: 'R$ 49',
            period: '/mês',
            description: 'Perfeito para projetos pessoais e blogs independentes.',
            features: ['Até 5 páginas publicadas', '10.000 visualizações/mês', 'Editor visual com 15 blocos', 'SSL e CDN inclusos'],
            buttonText: 'Começar Grátis',
            isPopular: false,
          },
          {
            name: 'Profissional',
            price: 'R$ 149',
            period: '/mês',
            description: 'Ideal para empresas em crescimento e e-commerces.',
            features: ['Páginas e posts ilimitados', '100.000 visualizações/mês', 'API REST & GraphQL completas', 'Suporte a múltiplos autores', 'Assistente de IA integrado'],
            buttonText: 'Assinar Pro',
            isPopular: true,
          },
          {
            name: 'Enterprise',
            price: 'R$ 499',
            period: '/mês',
            description: 'Para grandes portais com tráfego massivo e SLA dedicado.',
            features: ['Tudo do plano Profissional', 'Visualizações ilimitadas', 'Conexão direta PostgreSQL/Mongo', 'SSO e auditoria de segurança', 'Gerente de conta dedicado'],
            buttonText: 'Falar com Consultor',
            isPopular: false,
          },
        ],
      },
      styles: {
        paddingY: 'medium',
      },
    },
  },
  {
    id: 'reuse_newsletter_box',
    title: 'Caixa de Captura de Newsletter',
    category: 'marketing',
    description: 'Componente com campo de e-mail e validação para captação de leads.',
    usageCount: 5,
    createdAt: '2026-02-20T16:00:00Z',
    updatedAt: '2026-03-18T12:00:00Z',
    block: {
      id: 'block_newsletter_std',
      type: 'newsletter',
      content: {
        title: 'Receba nossos melhores artigos semanais',
        description: 'Junte-se a mais de 15.000 desenvolvedores e criadores de conteúdo que recebem dicas exclusivas toda terça-feira.',
        placeholder: 'Seu melhor e-mail...',
        buttonText: 'Inscrever-se',
        privacyNote: 'Prometemos zero spam. Cancele quando quiser.',
      },
      styles: {
        paddingY: 'medium',
        borderRadius: 'lg',
        border: true,
      },
    },
  },
];

export const INITIAL_PAGES: Page[] = [
  {
    id: 'page_home',
    slug: 'home',
    title: 'Início - Plataforma NextBlock CMS',
    description: 'A experiência definitiva de gerenciamento de conteúdo com velocidade Next.js e facilidade WordPress.',
    template: 'landing',
    status: 'published',
    isHomePage: true,
    order: 1,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-22T14:00:00Z',
    seo: {
      metaTitle: 'NextBlock CMS - O WordPress Moderno em Next.js',
      metaDescription: 'Crie sites e portais ultra-rápidos com editor drag-and-drop de blocos, API REST/GraphQL e IA.',
      keywords: ['nextjs cms', 'wordpress moderno', 'headless cms', 'editor de blocos', 'react cms'],
      ogImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&auto=format&fit=crop&q=80',
    },
    blocks: [
      {
        id: 'blk_home_hero',
        type: 'hero',
        content: {
          badge: '⚡ NOVA GERAÇÃO DE CMS 2026',
          title: 'O poder do WordPress com a velocidade do Next.js',
          subtitle: 'Editor visual drag-and-drop intuitivo, blocos reutilizáveis modulares, APIs Headless REST/GraphQL e IA nativa para gerar e refinar seu conteúdo.',
          primaryCtaText: 'Explorar Demonstração',
          primaryCtaUrl: '#blocos',
          secondaryCtaText: 'Acessar API Explorer',
          secondaryCtaUrl: '#api',
          imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
          imageAlt: 'Ambiente de desenvolvimento moderno',
        },
        styles: {
          paddingY: 'large',
          textAlign: 'center',
        },
      },
      {
        id: 'blk_home_stats',
        type: 'stats',
        content: {
          items: [
            { label: 'Velocidade Lighthouse', value: '100/100', description: 'Carregamento instantâneo via SSG e ISR' },
            { label: 'Tipos de Blocos', value: '18+', description: 'Totalmente customizáveis e reutilizáveis' },
            { label: 'Disponibilidade de API', value: '99.99%', description: 'REST e GraphQL de alta performance' },
            { label: 'Redução de Tempo Dev', value: '75%', description: 'Sem necessidade de backend complexo' },
          ],
        },
        styles: {
          paddingY: 'medium',
          backgroundColor: '#f8fafc',
          borderRadius: 'lg',
        },
      },
      {
        id: 'blk_home_cols',
        type: 'columns',
        content: {
          title: 'Por que times modernos estão migrando para o NextBlock?',
          subtitle: 'A combinação perfeita entre liberdade visual para criadores e excelência técnica para desenvolvedores.',
          columnsCount: 3,
          items: [
            {
              icon: 'Blocks',
              title: 'Editor Visual Drag & Drop',
              text: 'Monte páginas como quem monta blocos LEGO. Reordene, edite textos em tempo real e visualize no mobile instantaneamente.',
            },
            {
              icon: 'Zap',
              title: 'Headless REST & GraphQL',
              text: 'Consuma os conteúdos em qualquer frontend: Next.js, Mobile App, React Native ou Smart TVs com endpoints otimizados.',
            },
            {
              icon: 'Sparkles',
              title: 'Assistente IA Integrado',
              text: 'Gere rascunhos de artigos, reescreva parágrafos, gere tabelas e FAQs completas com o Gemini 3.7 Flash em segundos.',
            },
          ],
        },
        styles: {
          paddingY: 'large',
        },
      },
      {
        id: 'blk_home_faq',
        type: 'faq',
        content: {
          title: 'Perguntas Frequentes',
          subtitle: 'Tudo o que você precisa saber sobre o funcionamento do CMS.',
          items: [
            {
              question: 'Como o NextBlock se compara ao WordPress tradicional com PHP?',
              answer: 'O NextBlock utiliza React e Next.js no frontend e backend, garantindo carregamento quase instantâneo, segurança total contra vulnerabilidades comuns de PHP e facilidade de deploy em plataformas modernas como Vercel e Railway.',
            },
            {
              question: 'Posso exportar os dados e conectar em um banco PostgreSQL ou MongoDB?',
              answer: 'Sim! O sistema inclui um gerador de DDL schemas, migrations prontas para PostgreSQL e Mongoose para MongoDB, além de permitir exportação completa em formato JSON.',
            },
            {
              question: 'Como funciona o controle de permissões por papéis?',
              answer: 'O sistema suporta Administradores (controle total de usuários, configurações e banco), Editores (criação e edição de posts, páginas e blocos) e Visitantes (acesso aos conteúdos públicos e envio de formulários).',
            },
          ],
        },
        styles: {
          paddingY: 'large',
        },
      },
      {
        id: 'blk_home_cta',
        type: 'cta_banner',
        content: {
          tagline: 'COMECE HOJE',
          title: 'Crie seu primeiro post ou página em menos de 2 minutos',
          description: 'Acesse o editor visual agora mesmo e experimente a flexibilidade dos blocos dinâmicos.',
          primaryButtonText: 'Abrir Editor Visual',
          primaryButtonUrl: '#editor',
          secondaryButtonText: 'Ver Documentação',
          secondaryButtonUrl: '#docs',
          styleVariant: 'gradient',
        },
        styles: {
          paddingY: 'large',
          borderRadius: 'lg',
        },
      },
    ],
  },
  {
    id: 'page_about',
    slug: 'sobre',
    title: 'Sobre Nós - Nossa Missão e Equipe',
    description: 'Conheça quem está por trás da plataforma que está redefinindo a publicação de conteúdo na web.',
    template: 'default',
    status: 'published',
    isHomePage: false,
    order: 2,
    createdAt: '2026-01-20T11:00:00Z',
    updatedAt: '2026-03-21T16:00:00Z',
    seo: {
      metaTitle: 'Sobre Nós | NextBlock CMS',
      metaDescription: 'Conheça nossa história e o compromisso em criar a melhor ferramenta de publicação web.',
      keywords: ['sobre', 'equipe', 'missao', 'nextjs'],
      ogImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&auto=format&fit=crop&q=80',
    },
    blocks: [
      {
        id: 'blk_about_heading',
        type: 'heading',
        content: {
          level: 1,
          text: 'Transformando a criação de conteúdo para a era moderna da web',
        },
        styles: {
          textAlign: 'center',
          paddingY: 'medium',
        },
      },
      {
        id: 'blk_about_para1',
        type: 'paragraph',
        content: {
          text: 'Fundada com o objetivo de unir o melhor de dois mundos: a simplicidade e o poder da arquitetura de blocos inaugurada pelo WordPress, com o desempenho, a segurança e a flexibilidade do ecossistema React e Next.js.',
        },
        styles: {
          maxWidth: 'medium',
          textAlign: 'center',
        },
      },
      {
        id: 'blk_about_img',
        type: 'image',
        content: {
          url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&auto=format&fit=crop&q=80',
          caption: 'Nosso time multidisciplinar trabalhando na evolução contínua da plataforma.',
          altText: 'Time colaborando em ambiente moderno',
        },
        styles: {
          paddingY: 'medium',
          borderRadius: 'md',
        },
      },
      {
        id: 'blk_about_quote',
        type: 'quote',
        content: {
          quote: 'A melhor tecnologia é aquela que capacita tanto os criadores não-técnicos a expressarem suas ideias quanto os desenvolvedores a manterem código limpo e seguro.',
          author: 'Ana Silva, Tech Lead do NextBlock',
          role: 'Arquiteta de Software',
        },
        styles: {
          paddingY: 'medium',
        },
      },
    ],
  },
  {
    id: 'page_services',
    slug: 'servicos',
    title: 'Serviços & Soluções Corporativas',
    description: 'Soluções sob medida para portais de notícias, e-commerces e sites institucionais de alta escala.',
    template: 'default',
    status: 'published',
    isHomePage: false,
    order: 3,
    createdAt: '2026-02-05T09:00:00Z',
    updatedAt: '2026-03-20T10:00:00Z',
    seo: {
      metaTitle: 'Serviços e Soluções CMS para Grandes Empresas',
      metaDescription: 'Implementação de Headless CMS, migração de WordPress para Next.js e treinamento.',
      keywords: ['migracao wordpress', 'servicos cms', 'nextjs enterprise'],
    },
    blocks: [
      {
        id: 'blk_srv_hero',
        type: 'heading',
        content: {
          level: 1,
          text: 'Soluções Robustas para Organizações que Não Podem Parar',
        },
        styles: {
          textAlign: 'center',
          paddingY: 'medium',
        },
      },
      {
        id: 'blk_srv_pricing',
        type: 'pricing',
        content: {
          title: 'Planos de Implementação e Suporte',
          subtitle: 'Escolha o pacote que melhor atende à escala do seu negócio.',
          plans: [
            {
              name: 'Migração Express',
              price: 'R$ 2.400',
              period: ' projeto',
              description: 'Migração completa de posts e mídias de WordPress legado para Next.js.',
              features: ['Até 500 posts/páginas', 'Exportação e limpeza de dados', 'SEO Redirects 301 configurados', 'Treinamento de 2h da equipe'],
              buttonText: 'Contratar Migração',
              isPopular: false,
            },
            {
              name: 'Custom CMS Pro',
              price: 'R$ 6.800',
              period: ' projeto',
              description: 'Desenvolvimento de blocos customizados e integração com sistemas legados.',
              features: ['Blocos React exclusivos sob medida', 'Integração PostgreSQL/MongoDB', 'Pipelines CI/CD Vercel/Railway', 'Suporte prioritário 60 dias'],
              buttonText: 'Solicitar Proposta',
              isPopular: true,
            },
          ],
        },
        styles: {
          paddingY: 'medium',
        },
      },
    ],
  },
  {
    id: 'page_contact',
    slug: 'contato',
    title: 'Fale Conosco',
    description: 'Entre em contato com nossa equipe para dúvidas, suporte técnico ou parcerias comerciais.',
    template: 'default',
    status: 'published',
    isHomePage: false,
    order: 4,
    createdAt: '2026-02-10T14:00:00Z',
    updatedAt: '2026-03-22T08:00:00Z',
    seo: {
      metaTitle: 'Contato | NextBlock CMS',
      metaDescription: 'Mande sua mensagem e responderemos em até 2 horas úteis.',
      keywords: ['contato', 'suporte', 'fale conosco'],
    },
    blocks: [
      {
        id: 'blk_cnt_head',
        type: 'heading',
        content: {
          level: 1,
          text: 'Vamos construir algo incrível juntos?',
        },
        styles: {
          textAlign: 'center',
          paddingY: 'medium',
        },
      },
      {
        id: 'blk_cnt_newsletter',
        type: 'newsletter',
        content: {
          title: 'Envie sua mensagem ou solicite uma demonstração',
          description: 'Nossa equipe técnica responderá prontamente com todas as instruções necessárias.',
          placeholder: 'Digite seu e-mail corporativo...',
          buttonText: 'Solicitar Contato',
          privacyNote: 'Seus dados estão protegidos pela LGPD.',
        },
        styles: {
          paddingY: 'large',
          borderRadius: 'lg',
          border: true,
        },
      },
    ],
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post_1',
    slug: 'o-futuro-dos-cms-headless-e-nextjs-em-2026',
    title: 'O Futuro dos CMS Headless e Next.js em 2026: Por Que a Web Mudou',
    excerpt: 'Descubra como a combinação de componentes visuais React com APIs GraphQL e SSG superou as limitações dos CMS tradicionais em PHP.',
    featuredImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&auto=format&fit=crop&q=80',
    status: 'published',
    category: 'Tecnologia & Dev',
    tags: ['Next.js', 'Headless CMS', 'React 19', 'Performance'],
    authorId: 'usr_admin',
    authorName: 'Ana Silva',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    views: 3420,
    readingTime: '5 min',
    publishedAt: '2026-03-15T14:30:00Z',
    createdAt: '2026-03-14T10:00:00Z',
    updatedAt: '2026-03-15T14:30:00Z',
    seo: {
      metaTitle: 'O Futuro dos CMS Headless e Next.js em 2026',
      metaDescription: 'Análise técnica sobre como a arquitetura moderna de blocos e Next.js transformou a velocidade e manutenibilidade de sites.',
      keywords: ['cms headless', 'nextjs 2026', 'react 19 cms', 'desempenho web'],
      ogImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&auto=format&fit=crop&q=80',
    },
    blocks: [
      {
        id: 'blk_p1_1',
        type: 'heading',
        content: {
          level: 2,
          text: 'A evolução da gestão de conteúdo: Da era monolítica aos blocos modulares',
        },
      },
      {
        id: 'blk_p1_2',
        type: 'paragraph',
        content: {
          text: 'Durante mais de duas décadas, o WordPress foi o líder absoluto da web por um motivo claro: qualquer pessoa conseguia publicar conteúdo sem precisar programar. No entanto, com a evolução dos frameworks modernos, as expectativas de velocidade, segurança e experiência de desenvolvimento mudaram drasticamente.',
        },
      },
      {
        id: 'blk_p1_quote',
        type: 'quote',
        content: {
          quote: 'Em 2026, cada milissegundo de atraso no carregamento de uma página representa perda direta de conversão e queda de posicionamento no Google.',
          author: 'Relatório Global de Web Performance',
        },
      },
      {
        id: 'blk_p1_code',
        type: 'code',
        content: {
          language: 'typescript',
          code: `// Consumindo dados do NextBlock via API Headless
export async function getStaticProps() {
  const res = await fetch('https://meu-cms.com/api/posts/o-futuro-dos-cms');
  const post = await res.json();

  return {
    props: { post },
    revalidate: 60, // ISR em tempo real
  };
}`,
        },
      },
      {
        id: 'blk_p1_para3',
        type: 'paragraph',
        content: {
          text: 'Com a abordagem modular por blocos, redatores continuam com a liberdade de diagramar artigos ricos visualmente, enquanto engenheiros de software têm a certeza de que todo componente gerado respeita o design system e as regras de acessibilidade.',
        },
      },
      {
        id: 'blk_p1_cta',
        type: 'cta_banner',
        content: {
          tagline: 'EXPERIMENTE NA PRÁTICA',
          title: 'Quer criar seu próximo projeto com essa arquitetura?',
          description: 'Use nossos blocos reutilizáveis pré-configurados e lance seu portal hoje.',
          primaryButtonText: 'Começar Agora',
          primaryButtonUrl: '#editor',
          styleVariant: 'dark',
        },
      },
    ],
  },
  {
    id: 'post_2',
    slug: 'como-otimizar-seo-e-core-web-vitals-em-sites-react',
    title: 'Guia Definitivo: Como Obter 100 no Core Web Vitals com Next.js',
    excerpt: 'Passo a passo com técnicas práticas para eliminar Cumulative Layout Shift (CLS), acelerar o LCP e dominar as buscas orgânicas.',
    featuredImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80',
    status: 'published',
    category: 'Marketing & SEO',
    tags: ['SEO', 'Core Web Vitals', 'Lighthouse', 'Otimização'],
    authorId: 'usr_editor',
    authorName: 'Carlos Mendes',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    views: 2150,
    readingTime: '4 min',
    publishedAt: '2026-03-18T10:15:00Z',
    createdAt: '2026-03-17T09:00:00Z',
    updatedAt: '2026-03-18T10:15:00Z',
    seo: {
      metaTitle: 'Como Otimizar SEO e Core Web Vitals no Next.js',
      metaDescription: 'Estratégias avançadas de renderização, tags OpenGraph e otimização de imagens no Next.js.',
      keywords: ['seo react', 'core web vitals', 'lcp fid cls', 'nextjs seo'],
      ogImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80',
    },
    blocks: [
      {
        id: 'blk_p2_1',
        type: 'heading',
        content: {
          level: 2,
          text: 'Os três pilares indispensáveis para rankear em primeiro lugar',
        },
      },
      {
        id: 'blk_p2_2',
        type: 'paragraph',
        content: {
          text: 'O algoritmo de busca do Google prioriza sites que carregam o conteúdo principal (LCP) em menos de 1.8 segundos e mantêm a estabilidade visual sem pulos bruscos durante a renderização.',
        },
      },
      {
        id: 'blk_p2_table',
        type: 'table',
        content: {
          headers: ['Métrica', 'Tempo Ideal', 'Impacto no SEO', 'Como o CMS Ajuda'],
          rows: [
            ['LCP (Largest Contentful Paint)', '< 2.0s', 'Crítico', 'Otimização automática de imagens WebP/AVIF'],
            ['INP (Interaction to Next Paint)', '< 150ms', 'Alto', 'Zero scripts bloqueantes no editor visual'],
            ['CLS (Cumulative Layout Shift)', '< 0.05', 'Alto', 'Dimensões reservadas para todos os blocos'],
          ],
        },
      },
    ],
  },
];

export const INITIAL_SETTINGS: GlobalSettings = {
  siteName: 'NextBlock CMS',
  siteTitle: 'NextBlock CMS',
  siteDescription: 'Gerenciador de Conteúdo Moderno em Next.js com Editor Visual & IA',
  siteTagline: 'Gerenciador de Conteúdo Moderno em Next.js com Editor Visual & IA',
  siteLogo: '⚡ NextBlock',
  siteFavicon: '⚡',
  primaryColor: '#2563eb',
  fontFamily: 'Inter',
  allowComments: true,
  showAuthorBio: true,
  defaultLanguage: 'pt-BR',
  databaseProvider: 'postgresql',
  dbType: 'postgresql',
  databaseUrl: 'postgresql://admin:secret@localhost:5432/nextblock_cms',
  apiEnabled: true,
  graphqlEnabled: true,
  aiModel: 'gemini-3.7-flash',
};

export const INITIAL_COMMENTS: Comment[] = [
  {
    id: 'comm_1',
    postId: 'post_1',
    postTitle: 'Construindo Aplicações Web de Alta Performance com Next.js 15',
    authorName: 'Rodrigo Lima',
    authorEmail: 'rodrigo.dev@gmail.com',
    authorAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    content: 'Excelente artigo! A explicação sobre Server Components e streaming SSR com o App Router esclareceu muitas dúvidas da nossa equipe.',
    status: 'approved',
    createdAt: '2026-03-22T14:20:00Z',
    response: 'Obrigado pelo feedback, Rodrigo! Ficamos felizes em ajudar.',
  },
  {
    id: 'comm_2',
    postId: 'post_1',
    postTitle: 'Construindo Aplicações Web de Alta Performance com Next.js 15',
    authorName: 'Mariana Duarte',
    authorEmail: 'mariana.ux@tech.com',
    authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    content: 'Vocês pretendem lançar um tutorial aprofundado sobre Partial Prerendering (PPR) integrado ao editor de blocos?',
    status: 'pending',
    createdAt: '2026-03-23T09:15:00Z',
  },
  {
    id: 'comm_3',
    postId: 'post_2',
    postTitle: 'A Revolução dos CMS Modulares Baseados em Blocos e IA',
    authorName: 'Felipe Santos',
    authorEmail: 'felipe.santos@growth.co',
    authorAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    content: 'O suporte a blocos reutilizáveis estilo WordPress Gutenberg com componentes React nativos é o verdadeiro divisor de águas!',
    status: 'approved',
    createdAt: '2026-03-22T11:45:00Z',
  },
  {
    id: 'comm_4',
    postId: 'post_3',
    postTitle: 'Guia Completo de SEO e Core Web Vitals para 2026',
    authorName: 'PromoBot 3000',
    authorEmail: 'spam-bot-marketing@offers.xyz',
    content: 'Compre seguidores e backlinks baratos no nosso portal promocional! Clique aqui agora.',
    status: 'spam',
    createdAt: '2026-03-21T22:00:00Z',
  },
];

export const INITIAL_THEMES: Theme[] = [
  {
    id: 'theme_twentytwentyfour',
    name: 'Twenty Twenty-Four Next',
    slug: 'twentytwentyfour-next',
    description: 'Tema clássico e elegante focado em tipografia editorial refinada, espaços generosos e renderização ultra rápida em Next.js.',
    author: 'WordPress & NextBlock Team',
    version: '1.4.0',
    screenshot: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&auto=format&fit=crop&q=80',
    primaryColor: '#2563eb',
    fontFamily: 'Inter',
    tags: ['Blog', 'Editorial', 'Acessível', 'FSE'],
    isActive: true,
  },
  {
    id: 'theme_astramodern',
    name: 'Astra Modern Headless',
    slug: 'astra-modern',
    description: 'Tema altamente personalizável e veloz para startups, portfólios corporativos e agências digitais.',
    author: 'Brainstorm Next',
    version: '2.1.2',
    screenshot: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80',
    primaryColor: '#6366f1',
    fontFamily: 'Plus Jakarta Sans',
    tags: ['Startup', 'Agência', 'Landing Page'],
    isActive: false,
  },
  {
    id: 'theme_editorial_times',
    name: 'Editorial & News Magazine',
    slug: 'editorial-times',
    description: 'Layout clássico estilo portal de notícias com colunas dinâmicas, seções em grade e suporte a múltiplos autores.',
    author: 'PressCraft',
    version: '3.0.1',
    screenshot: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&auto=format&fit=crop&q=80',
    primaryColor: '#0f172a',
    fontFamily: 'Playfair Display',
    tags: ['Jornal', 'Notícias', 'Multi-autor'],
    isActive: false,
  },
  {
    id: 'theme_storefront',
    name: 'Storefront Headless eCommerce',
    slug: 'storefront-headless',
    description: 'Tema com suporte nativo ao WooCommerce Headless, catálogo de produtos em blocos e carrinho interativo.',
    author: 'WooCommerce Core',
    version: '1.9.5',
    screenshot: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800&auto=format&fit=crop&q=80',
    primaryColor: '#7c3aed',
    fontFamily: 'Outfit',
    tags: ['eCommerce', 'Loja Virtual', 'Produtos'],
    isActive: false,
  },
];

export const INITIAL_PLUGINS: PluginItem[] = [
  {
    id: 'plugin_yoast',
    name: 'Yoast SEO Pro (Next.js Edition)',
    slug: 'yoast-seo-pro',
    description: 'Solução completa de SEO com análise de legibilidade em tempo real, semáforo de pontuação, tags Open Graph, XML Sitemap e Schema.org.',
    author: 'Team Yoast',
    version: '22.4.1',
    icon: 'Sparkles',
    isActive: true,
    category: 'seo',
    rating: 4.9,
    activeInstalls: '5M+',
    isPro: true,
  },
  {
    id: 'plugin_woocommerce',
    name: 'WooCommerce Headless Bridge',
    slug: 'woocommerce-headless',
    description: 'Conecte seu catálogo de produtos, pedidos, carrinho e gateways de pagamento (Stripe, PIX) diretamente nas páginas do CMS.',
    author: 'Automattic',
    version: '8.7.0',
    icon: 'ShoppingBag',
    isActive: true,
    category: 'ecommerce',
    rating: 4.8,
    activeInstalls: '4M+',
    isPro: false,
  },
  {
    id: 'plugin_acf',
    name: 'Advanced Custom Fields (ACF Pro)',
    slug: 'advanced-custom-fields',
    description: 'Crie campos personalizados avançados (Repeater, Imagem, Relação, Galeria) e vincule diretamente a qualquer post ou página.',
    author: 'WP Engine',
    version: '6.2.8',
    icon: 'Database',
    isActive: true,
    category: 'utilities',
    rating: 4.9,
    activeInstalls: '2M+',
    isPro: true,
  },
  {
    id: 'plugin_wp_rocket',
    name: 'WP Super Cache & ISR Accelerator',
    slug: 'wp-super-cache-isr',
    description: 'Otimizador de cache estático, minificação de scripts, compressão WebP/AVIF e revalidação sob demanda com Next.js.',
    author: 'WP Media',
    version: '3.15.2',
    icon: 'Zap',
    isActive: true,
    category: 'performance',
    rating: 4.9,
    activeInstalls: '3M+',
    isPro: true,
  },
  {
    id: 'plugin_gemini_ai',
    name: 'WP Gemini AI Supercharge',
    slug: 'wp-gemini-ai',
    description: 'Assistente inteligente alimentado pelo Gemini 3.7 Flash para redação de posts, tradução automática, geração de títulos e tags SEO.',
    author: 'Google Cloud & NextBlock',
    version: '1.5.0',
    icon: 'Sparkles',
    isActive: true,
    category: 'ai',
    rating: 5.0,
    activeInstalls: '850K+',
    isPro: true,
  },
  {
    id: 'plugin_wp_mail',
    name: 'WP Mail SMTP Transacional',
    slug: 'wp-mail-smtp',
    description: 'Garante que todos os e-mails de formulários, confirmações e comentários sejam entregues com segurança via API SMTP/SendGrid.',
    author: 'WPForms',
    version: '4.0.1',
    icon: 'Mail',
    isActive: false,
    category: 'forms',
    rating: 4.7,
    activeInstalls: '3M+',
    isPro: false,
  },
  {
    id: 'plugin_rankpulse_seo',
    name: 'RankPulse SEO Pro Suite',
    slug: 'rankpulse-seo-pro',
    description: 'Análise de legibilidade em tempo real, pontuação SEO 0-100, geração de Schema.org JSON-LD (Artigo, FAQ, Breadcrumbs), prévias Google SERP e Social Cards.',
    author: 'NextBlock Core & Search Lab',
    version: '3.2.0',
    icon: 'Sparkles',
    isActive: true,
    category: 'seo',
    rating: 5.0,
    activeInstalls: '1.2M+',
    isPro: true,
  },
  {
    id: 'plugin_webhooks_automation',
    name: 'Webhooks & Event Trigger Engine',
    slug: 'webhooks-automation',
    description: 'Dispare webhooks seguros para Zapier, Make, n8n, Discord e Slack sempre que posts forem criados, publicados ou atualizados.',
    author: 'NextBlock Cloud',
    version: '2.1.0',
    icon: 'Zap',
    isActive: true,
    category: 'utilities',
    rating: 4.9,
    activeInstalls: '620K+',
    isPro: false,
  },
  {
    id: 'plugin_edge_cache',
    name: 'Cloudflare & Vercel Edge Purge',
    slug: 'edge-cache-purge',
    description: 'Invalidação instantânea de CDN em milissegundos via tags de cache e revalidação sob demanda com Next.js 15 on-demand revalidation.',
    author: 'Edge Accelerator',
    version: '1.9.4',
    icon: 'Zap',
    isActive: true,
    category: 'performance',
    rating: 4.9,
    activeInstalls: '480K+',
    isPro: true,
  },
];

export const INITIAL_MENUS: MenuItem[] = [
  { id: 'menu_1', label: 'Início', url: '/' },
  { id: 'menu_2', label: 'Sobre Nós', url: '/sobre' },
  { id: 'menu_3', label: 'Serviços', url: '/servicos' },
  { id: 'menu_4', label: 'Blog & Notícias', url: '/blog' },
  { id: 'menu_5', label: 'Contato', url: '/contato' },
];
